### ISSUE TITLE
List attributes are reported as their non-list equivalent.

### ISSUE THREAD

**Issue by wouterdb** [inmanta/inmanta-sphinx#29]
e.g. source: https://github.com/inmanta/vyos/blob/master/model/_init.cf#L192
docs: https://docs.inmanta.com/community/latest/reference/modules/vyos.html#attribute-vyos::Ospf.network

**Comment by sanderr** [comment]
Probably due to the fact that `inmanta-sphinx/sphinxcontrib/inmanta/api.py:251` fetches `attr.get_type()` which just returns the base type. Perhaps a rename refactor in core is in order to make that fact more clear: `type` -> `basetype`?
`Attribute.validate` creates the actual type but doesn't expose it. The creation of the type could be abstracted to another method, which could then be called from `inmanta-sphinx` as well.

Whichever method is eventually used should be documented in [the `Attribute` section of the API reference](https://docs.inmanta.com/community/dev/reference/api.html#attributes)
